name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  PWD: ${GITHUB_REPOSITORY}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      
      - name: Ubuntu version
        run: lsb_release -a

      - name: Current path
        run: pwd

      - name: LS
        run: ls -al

      - name: workflow path
        run: echo ${PWD}

      - name: GTest
        run: |
          sudo apt-get install libgtest-dev -y
          sudo apt-get install cmake -y

      - name: build directory
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
          make
          
      - name: run unit test
        run: |
          ./unit_test
